const cloudinary = require("cloudinary").v2;
var fs = require("fs");
const multer = require("multer");
const path = require("path");

cloudinary.config({
  cloud_name: "dijjqfsto",
  api_key: "943785761215535",
  api_secret: "MSfacY2b-OGHnjJLiLni9zfH1R0"
});

const storageAvatar = multer.diskStorage({
  destination: "../assets/avatar",
  filename: function(req, file, cb) {
    console.log(req.params.id);

    cb(null, req.params.id + path.extname(file.originalname));
  }
});

const storageCv = multer.diskStorage({
  destination: "../assets/cv",
  filename: function(req, file, cb) {
    console.log("id - la = " + req.params.id);
    console.log("file - " + file);

    cb(null, req.params.id + path.extname(file.originalname));
  }
});

const avatarUpload = multer({ storage: storageAvatar }).single("avatar");
//const cvUpload = multer({ storage: storageCv }).single("cv");

// exports.profileimgup = (req, res) => {
//   avatarUpload(req, res, err => {
//     if (err) {
//       console.log(err);
//     } else {
//       console.log(req.file);
//     }
//   });

//   console.log("req came avatar");
// };
// exports.cvupload = (req, res) => {
//   console.log("req came cv");

//   cvUpload(req, res, err => {
//     if (err) {
//       console.log(err);
//     } else {
//       console.log(req.file);
//     }
//   });

//   console.log("req go cv");
// };

exports.imgupload = (req, res) => {
  console.log("id - " + req.params.id);

  console.log("[ile - " + req.file);

  console.log("in - file upload");

  avatarUpload(req, res, err => {
    console.log("avatr up");

    console.log("res- " + res + " req - " + req + " err - " + err);

    if (err) {
      console.log(err);
    } else {
      console.log(req.file);
    }
  });

  // console.log("in img upload");
  // //assets/avatar/5caa51ad56a61d6a2492ec98.jpg
  // cloudinary.uploader.upload(
  //   "/home/dealwithit/Desktop/sepro/recaux/assets/avatar/"+req.params.id+'.png',
  //   {
  //     tags: "basic_sample",
  //     folder: "recaux/avatar",
  //     public_id: "5caa51ad56a61d6a2492ec98",
  //     sign_url: true
  //   },
  //   function(err, image) {
  //     console.log();
  //     console.log("** File Upload");
  //     if (err) {
  //       console.warn(err);
  //     }
  //     console.log(
  //       "* public_id for the uploaded image is generated by Cloudinary's service."
  //     );
  //     console.log("* " + image.public_id);
  //     console.log("* " + image.url);

  //     // waitForAllUploads("pizza",err,image);
  //   }
  // );

  res.send("in img upload");
};
//     }
//   )(req, res, next);
// };
